-- Parte 3/9 de supabase/seed.sql
-- Cole este arquivo inteiro no SQL Editor e clique Run, depois passe pro próximo

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pulseira', 'Still Branco (Packshot)', NULL, 'pulseira_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 31, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pulseira', 'Still Humanizado', NULL, 'pulseira_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível, com o pulso como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o pulso levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 32, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pulseira', 'Still com Sombra Editorial', NULL, 'pulseira_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 33, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pulseira', 'Still em Superfície Texturizada', NULL, 'pulseira_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 34, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pulseira', 'Lifestyle com Modelo', NULL, 'pulseira_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 35, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Bracelete/Bangle', 'Still Branco (Packshot)', NULL, 'bracelete-bangle_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Bracelete apoiado na vertical, mostrando sua estrutura rígida e o formato circular.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 36, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Bracelete/Bangle', 'Still Humanizado', NULL, 'bracelete-bangle_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Bracelete apoiado na vertical, mostrando sua estrutura rígida e o formato circular, com o pulso e o antebraço como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o pulso e o antebraço levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 37, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Bracelete/Bangle', 'Still com Sombra Editorial', NULL, 'bracelete-bangle_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Bracelete apoiado na vertical, mostrando sua estrutura rígida e o formato circular.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 38, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Bracelete/Bangle', 'Still em Superfície Texturizada', NULL, 'bracelete-bangle_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Bracelete apoiado na vertical, mostrando sua estrutura rígida e o formato circular, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 39, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Bracelete/Bangle', 'Lifestyle com Modelo', NULL, 'bracelete-bangle_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso e o antebraço.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 40, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Anel', 'Still Branco (Packshot)', NULL, 'anel_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 41, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Anel', 'Still Humanizado', NULL, 'anel_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal, com a mão e os dedos como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com a mão e os dedos levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 42, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Anel', 'Still com Sombra Editorial', NULL, 'anel_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 43, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Anel', 'Still em Superfície Texturizada', NULL, 'anel_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 44, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Anel', 'Lifestyle com Modelo', NULL, 'anel_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a mão e os dedos.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 45, 'a_gerar') on conflict (nome_referencia) do nothing;
