-- Parte 2/9 de supabase/seed.sql
-- Cole este arquivo inteiro no SQL Editor e clique Run, depois passe pro próximo

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Colar Longo', 'Still Branco (Packshot)', NULL, 'colar-longo_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar longo disposto em curvas suaves, mostrando todo o comprimento.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 16, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Colar Longo', 'Still Humanizado', NULL, 'colar-longo_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar longo disposto em curvas suaves, mostrando todo o comprimento, com o colo e o decote como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o colo e o decote levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 17, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Colar Longo', 'Still com Sombra Editorial', NULL, 'colar-longo_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar longo disposto em curvas suaves, mostrando todo o comprimento.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 18, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Colar Longo', 'Still em Superfície Texturizada', NULL, 'colar-longo_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar longo disposto em curvas suaves, mostrando todo o comprimento, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 19, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Colar Longo', 'Lifestyle com Modelo', NULL, 'colar-longo_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo e o decote.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 20, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pingente', 'Still Branco (Packshot)', NULL, 'pingente_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pingente centralizado com a corrente disposta de forma orgânica ao redor.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 21, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pingente', 'Still Humanizado', NULL, 'pingente_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pingente centralizado com a corrente disposta de forma orgânica ao redor, com o colo, próximo ao centro do peito como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o colo, próximo ao centro do peito levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 22, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pingente', 'Still com Sombra Editorial', NULL, 'pingente_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pingente centralizado com a corrente disposta de forma orgânica ao redor.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 23, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pingente', 'Still em Superfície Texturizada', NULL, 'pingente_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pingente centralizado com a corrente disposta de forma orgânica ao redor, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 24, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Pingente', 'Lifestyle com Modelo', NULL, 'pingente_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo, próximo ao centro do peito.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 25, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Corrente Masculina', 'Still Branco (Packshot)', NULL, 'corrente-masculina_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Corrente disposta em linha reta ou levemente curva, evidenciando o elo.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 26, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Corrente Masculina', 'Still Humanizado', NULL, 'corrente-masculina_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Corrente disposta em linha reta ou levemente curva, evidenciando o elo, com o pescoço, estilo masculino como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o pescoço, estilo masculino levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Homem jovem (20-30), pele morena | Homem adulto (35-50), pele negra | Homem adulto (35-50), pele clara', '4:5 (vertical — e-commerce/Instagram)', 27, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Corrente Masculina', 'Still com Sombra Editorial', NULL, 'corrente-masculina_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Corrente disposta em linha reta ou levemente curva, evidenciando o elo.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 28, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Corrente Masculina', 'Still em Superfície Texturizada', NULL, 'corrente-masculina_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Corrente disposta em linha reta ou levemente curva, evidenciando o elo, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 29, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Corrente Masculina', 'Lifestyle com Modelo', NULL, 'corrente-masculina_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pescoço, estilo masculino.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Homem jovem (20-30), pele morena | Homem adulto (35-50), pele negra | Homem adulto (35-50), pele clara', '4:5 (vertical — Instagram/Stories)', 30, 'a_gerar') on conflict (nome_referencia) do nothing;
