-- Parte 6/9 de supabase/seed.sql
-- Cole este arquivo inteiro no SQL Editor e clique Run, depois passe pro próximo

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Lifestyle com Tema', 'Dia das Mães', 'dia-das-maes_anel_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a mão e os dedos.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 6, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Still com Tema', 'Dia das Mães', 'dia-das-maes_pulseira_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 7, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Lifestyle com Tema', 'Dia das Mães', 'dia-das-maes_pulseira_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 8, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Still com Tema', 'Dia dos Namorados', 'dia-dos-namorados_brinco_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Um par de brincos posicionado lado a lado, simetricamente.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 9, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Lifestyle com Tema', 'Dia dos Namorados', 'dia-dos-namorados_brinco_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a orelha e lateral do rosto.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 10, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Still com Tema', 'Dia dos Namorados', 'dia-dos-namorados_colar_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar disposto de forma orgânica sobre a superfície, mostrando o fecho e o comprimento total.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 11, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Lifestyle com Tema', 'Dia dos Namorados', 'dia-dos-namorados_colar_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo e o pescoço.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 12, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Still com Tema', 'Dia dos Namorados', 'dia-dos-namorados_anel_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 13, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Lifestyle com Tema', 'Dia dos Namorados', 'dia-dos-namorados_anel_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a mão e os dedos.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 14, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Still com Tema', 'Dia dos Namorados', 'dia-dos-namorados_pulseira_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 15, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Lifestyle com Tema', 'Dia dos Namorados', 'dia-dos-namorados_pulseira_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso.
Tema visual: Dia dos Namorados. Paleta de cores: tons de vermelho e vinho. Elementos/props de cena: pétalas de rosa vermelha, velas acesas desfocadas ao fundo. Clima geral: romântico, intimista, iluminação quente e noturna.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 16, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Still com Tema', 'Dia das Crianças', 'dia-das-criancas_brinco_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Um par de brincos posicionado lado a lado, simetricamente.
Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 17, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Lifestyle com Tema', 'Dia das Crianças', 'dia-das-criancas_brinco_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a orelha e lateral do rosto.
Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 18, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Still com Tema', 'Dia das Crianças', 'dia-das-criancas_colar_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar disposto de forma orgânica sobre a superfície, mostrando o fecho e o comprimento total.
Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 19, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Lifestyle com Tema', 'Dia das Crianças', 'dia-das-criancas_colar_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo e o pescoço.
Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 20, 'a_gerar') on conflict (nome_referencia) do nothing;
