-- Parte 8/9 de supabase/seed.sql
-- Cole este arquivo inteiro no SQL Editor e clique Run, depois passe pro próximo

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Lifestyle com Tema', 'Dia Internacional da Mulher', 'dia-internacional-da-mulher_colar_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo e o pescoço.
Tema visual: Dia Internacional da Mulher. Paleta de cores: tons de roxo e violeta. Elementos/props de cena: flor de mimosa (amarela) desfocada ao fundo. Clima geral: moderno, empoderado e sofisticado.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 36, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Still com Tema', 'Dia Internacional da Mulher', 'dia-internacional-da-mulher_anel_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal.
Tema visual: Dia Internacional da Mulher. Paleta de cores: tons de roxo e violeta. Elementos/props de cena: flor de mimosa (amarela) desfocada ao fundo. Clima geral: moderno, empoderado e sofisticado.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 37, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Lifestyle com Tema', 'Dia Internacional da Mulher', 'dia-internacional-da-mulher_anel_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a mão e os dedos.
Tema visual: Dia Internacional da Mulher. Paleta de cores: tons de roxo e violeta. Elementos/props de cena: flor de mimosa (amarela) desfocada ao fundo. Clima geral: moderno, empoderado e sofisticado.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 38, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Still com Tema', 'Dia Internacional da Mulher', 'dia-internacional-da-mulher_pulseira_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível.
Tema visual: Dia Internacional da Mulher. Paleta de cores: tons de roxo e violeta. Elementos/props de cena: flor de mimosa (amarela) desfocada ao fundo. Clima geral: moderno, empoderado e sofisticado.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 39, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Lifestyle com Tema', 'Dia Internacional da Mulher', 'dia-internacional-da-mulher_pulseira_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso.
Tema visual: Dia Internacional da Mulher. Paleta de cores: tons de roxo e violeta. Elementos/props de cena: flor de mimosa (amarela) desfocada ao fundo. Clima geral: moderno, empoderado e sofisticado.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 40, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Still com Tema', 'Black Friday', 'black-friday_brinco_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Um par de brincos posicionado lado a lado, simetricamente.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 41, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Lifestyle com Tema', 'Black Friday', 'black-friday_brinco_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a orelha e lateral do rosto.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 42, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Still com Tema', 'Black Friday', 'black-friday_colar_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar disposto de forma orgânica sobre a superfície, mostrando o fecho e o comprimento total.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 43, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Lifestyle com Tema', 'Black Friday', 'black-friday_colar_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo e o pescoço.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 44, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Still com Tema', 'Black Friday', 'black-friday_anel_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 45, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Lifestyle com Tema', 'Black Friday', 'black-friday_anel_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a mão e os dedos.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 46, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Still com Tema', 'Black Friday', 'black-friday_pulseira_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Pulseira disposta em curva, como se estivesse ao redor de um pulso invisível.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 47, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Pulseira', 'Lifestyle com Tema', 'Black Friday', 'black-friday_pulseira_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso.
Tema visual: Black Friday. Paleta de cores: preto e dourado. Elementos/props de cena: fundo preto fosco, iluminação dramática lateral, reflexo dourado sutil. Clima geral: luxuoso, de destaque, alto contraste.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 48, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Still com Tema', 'Natal', 'natal_brinco_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Um par de brincos posicionado lado a lado, simetricamente.
Tema visual: Natal. Paleta de cores: tons de vermelho, dourado e verde. Elementos/props de cena: ramos verdes, pinha desfocada, luzes de natal desfocadas ao fundo (efeito bokeh dourado). Clima geral: aconchegante, festivo e brilhante.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 49, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Lifestyle com Tema', 'Natal', 'natal_brinco_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a orelha e lateral do rosto.
Tema visual: Natal. Paleta de cores: tons de vermelho, dourado e verde. Elementos/props de cena: ramos verdes, pinha desfocada, luzes de natal desfocadas ao fundo (efeito bokeh dourado). Clima geral: aconchegante, festivo e brilhante.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 50, 'a_gerar') on conflict (nome_referencia) do nothing;
