-- Parte 4/9 de supabase/seed.sql
-- Cole este arquivo inteiro no SQL Editor e clique Run, depois passe pro próximo

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Aliança', 'Still Branco (Packshot)', NULL, 'alianca_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Duas alianças apoiadas lado a lado, uma levemente sobreposta à outra.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 46, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Aliança', 'Still Humanizado', NULL, 'alianca_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Duas alianças apoiadas lado a lado, uma levemente sobreposta à outra, com as mãos entrelaçadas, próximas ao dedo anelar como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com as mãos entrelaçadas, próximas ao dedo anelar levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher adulta (30-45), pele morena | Homem adulto (35-50), pele clara | Mulher idosa (60+), pele negra', '4:5 (vertical — e-commerce/Instagram)', 47, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Aliança', 'Still com Sombra Editorial', NULL, 'alianca_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Duas alianças apoiadas lado a lado, uma levemente sobreposta à outra.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 48, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Aliança', 'Still em Superfície Texturizada', NULL, 'alianca_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Duas alianças apoiadas lado a lado, uma levemente sobreposta à outra, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 49, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Aliança', 'Lifestyle com Modelo', NULL, 'alianca_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando as mãos entrelaçadas, próximas ao dedo anelar.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher adulta (30-45), pele morena | Homem adulto (35-50), pele clara | Mulher idosa (60+), pele negra', '4:5 (vertical — Instagram/Stories)', 50, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Tornozeleira', 'Still Branco (Packshot)', NULL, 'tornozeleira_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Tornozeleira disposta em curva, simulando o formato do tornozelo.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 51, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Tornozeleira', 'Still Humanizado', NULL, 'tornozeleira_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Tornozeleira disposta em curva, simulando o formato do tornozelo, com o tornozelo e o pé como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o tornozelo e o pé levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 52, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Tornozeleira', 'Still com Sombra Editorial', NULL, 'tornozeleira_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Tornozeleira disposta em curva, simulando o formato do tornozelo.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 53, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Tornozeleira', 'Still em Superfície Texturizada', NULL, 'tornozeleira_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Tornozeleira disposta em curva, simulando o formato do tornozelo, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 54, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Tornozeleira', 'Lifestyle com Modelo', NULL, 'tornozeleira_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o tornozelo e o pé.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 55, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Broche', 'Still Branco (Packshot)', NULL, 'broche_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Broche fixado sobre uma prega de tecido, mostrando o pino e o relevo frontal.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 56, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Broche', 'Still Humanizado', NULL, 'broche_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Broche fixado sobre uma prega de tecido, mostrando o pino e o relevo frontal, com a lapela de um blazer ou tecido como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com a lapela de um blazer ou tecido levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 57, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Broche', 'Still com Sombra Editorial', NULL, 'broche_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Broche fixado sobre uma prega de tecido, mostrando o pino e o relevo frontal.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 58, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Broche', 'Still em Superfície Texturizada', NULL, 'broche_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Broche fixado sobre uma prega de tecido, mostrando o pino e o relevo frontal, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 59, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Broche', 'Lifestyle com Modelo', NULL, 'broche_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a lapela de um blazer ou tecido.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 60, 'a_gerar') on conflict (nome_referencia) do nothing;
