-- Parte 5/9 de supabase/seed.sql
-- Cole este arquivo inteiro no SQL Editor e clique Run, depois passe pro próximo

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Conjunto (colar + brinco)', 'Still Branco (Packshot)', NULL, 'conjunto-colar-+-brinco_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar e brincos do conjunto dispostos juntos de forma harmônica.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 61, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Conjunto (colar + brinco)', 'Still Humanizado', NULL, 'conjunto-colar-+-brinco_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar e brincos do conjunto dispostos juntos de forma harmônica, com o pescoço, colo e a orelha como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o pescoço, colo e a orelha levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — e-commerce/Instagram)', 62, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Conjunto (colar + brinco)', 'Still com Sombra Editorial', NULL, 'conjunto-colar-+-brinco_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar e brincos do conjunto dispostos juntos de forma harmônica.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 63, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Conjunto (colar + brinco)', 'Still em Superfície Texturizada', NULL, 'conjunto-colar-+-brinco_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar e brincos do conjunto dispostos juntos de forma harmônica, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 64, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Conjunto (colar + brinco)', 'Lifestyle com Modelo', NULL, 'conjunto-colar-+-brinco_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pescoço, colo e a orelha.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 65, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Relógio', 'Still Branco (Packshot)', NULL, 'relogio_still-branco-packshot', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Relógio apoiado em pé, mostrando o mostrador de frente e a pulseira em curva.
Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (#FFFFFF), sem sombras duras, iluminação suave e uniforme tipo softbox, foco nítido em toda a peça, sem reflexos exagerados. Estilo clean, comercial, pronto para catálogo de loja online.', NULL, '1:1 (quadrado — catálogo)', 66, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Relógio', 'Still Humanizado', NULL, 'relogio_still-humanizado', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Relógio apoiado em pé, mostrando o mostrador de frente e a pulseira em curva, com o pulso como elemento de contexto ao fundo.
Fotografia still humanizada, profissional, estilo editorial de e-commerce de joias. Foco nítido na peça, com o pulso levemente desfocado(a) ao fundo (profundidade de campo rasa), iluminação natural suave, tom de pele realista: [PERFIL].', 'Mulher adulta (30-45), pele morena | Homem adulto (35-50), pele clara | Mulher idosa (60+), pele negra', '4:5 (vertical — e-commerce/Instagram)', 67, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Relógio', 'Still com Sombra Editorial', NULL, 'relogio_still-com-sombra-editorial', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Relógio apoiado em pé, mostrando o mostrador de frente e a pulseira em curva.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 68, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Relógio', 'Still em Superfície Texturizada', NULL, 'relogio_still-em-superficie-texturizada', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Relógio apoiado em pé, mostrando o mostrador de frente e a pulseira em curva, apoiado sobre pedra cinza natural.
Fotografia still profissional sobre superfície pedra cinza natural, com iluminação natural suave vinda de uma janela lateral, sombra natural sutil, composição minimalista e orgânica, cores quentes e aconchegantes.', NULL, '1:1 (quadrado — feed/catálogo)', 69, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Relógio', 'Lifestyle com Modelo', NULL, 'relogio_lifestyle-com-modelo', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o pulso.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher adulta (30-45), pele morena | Homem adulto (35-50), pele clara | Mulher idosa (60+), pele negra', '4:5 (vertical — Instagram/Stories)', 70, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Still com Tema', 'Dia das Mães', 'dia-das-maes_brinco_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Um par de brincos posicionado lado a lado, simetricamente.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 1, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Brinco', 'Lifestyle com Tema', 'Dia das Mães', 'dia-das-maes_brinco_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando a orelha e lateral do rosto.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 2, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Still com Tema', 'Dia das Mães', 'dia-das-maes_colar_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Colar disposto de forma orgânica sobre a superfície, mostrando o fecho e o comprimento total.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 3, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Colar', 'Lifestyle com Tema', 'Dia das Mães', 'dia-das-maes_colar_lifestyle-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: [PERFIL] usando a peça de forma natural, evidenciando o colo e o pescoço.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia lifestyle profissional para redes sociais e e-commerce, com [PERFIL] usando a peça em cena natural do dia a dia, expressão espontânea e sutil, iluminação natural suave (luz de janela ou luz externa suave), fundo desfocado (profundidade de campo rasa), clima autêntico e aspiracional.', 'Mulher jovem (18-25), pele clara | Mulher adulta (30-45), pele morena | Mulher adulta (30-45), pele negra | Mulher idosa (60+), pele clara', '4:5 (vertical — Instagram/Stories)', 4, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('data_comemorativa', 'Anel', 'Still com Tema', 'Dia das Mães', 'dia-das-maes_anel_still-com-tema', 'Usando como base a foto anexada da peça (semijoia real), gere uma nova fotografia profissional dessa MESMA peça. É obrigatório preservar com fidelidade absoluta: formato, cor e acabamento do metal, tipo e corte das pedras/cristais, textura, brilho, tamanho e proporções. NÃO altere, substitua, invente ou modifique a peça de nenhuma forma — a joia gerada precisa ser 100% reconhecível como a peça original.
Cena: Anel apoiado em pé, levemente inclinado, mostrando o aro e o detalhe frontal.
Tema visual: Dia das Mães. Paleta de cores: tons de rosa suave e nude. Elementos/props de cena: flores (rosas), um bilhete escrito à mão desfocado ao fundo, tecido de seda rosa-claro. Clima geral: afetivo, delicado e caloroso.
Fotografia still editorial profissional. Fundo neutro (cinza claro ou bege), com sombra suave e alongada da peça projetada de forma elegante, iluminação direcional lateral suave, alto contraste controlado, clima sofisticado e minimalista.', NULL, '1:1 (quadrado — catálogo/editorial)', 5, 'a_gerar') on conflict (nome_referencia) do nothing;
