-- Migração v6 -- insert parte 3/3
-- Novas categorias: Lifestyle + Peças em Você

insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Peças em Você', 'Regata Frontal — Colar', NULL, 'voce_07_regata-frontal', 'Serão anexadas duas fotografias: a FOTO 1, com o rosto da própria assinante, e a FOTO 2, com a(s) joia(s) do produto. A FOTO 1 determina exclusivamente a identidade da modelo: preserve fielmente formato do rosto, olhos, sobrancelhas, nariz, boca, mandíbula, proporções faciais, tom de pele e cabelo (cor, comprimento e textura reais) — a pessoa da imagem final deve continuar claramente reconhecível como a mesma pessoa da FOTO 1. Não a transforme em um rosto genérico, não rejuvenesça, não altere suas feições ou idade aparente. A FOTO 2 determina exclusivamente as joias: identifique exatamente quantas peças e de que tipo existem nela e utilize somente essas peças, na mesma quantidade — nunca invente, duplique, remova ou substitua nenhuma peça; preserve formato, proporções, espessura, acabamento, brilho, cor do metal, pedras e todos os detalhes originais. Se a FOTO 2 contiver outra pessoa, ignore completamente essa pessoa — rosto, corpo, pele, cabelo, roupa e pose não servem de referência, apenas as joias. Nunca misture as duas fotos: cabelo e tom de pele vêm sempre da FOTO 1; joias vêm sempre da FOTO 2. Se determinado tipo de joia não existir na FOTO 2, ele não deve aparecer na imagem final sob nenhuma hipótese.

Composição: retrato fechado quase frontal, corpo levemente apoiado contra uma parede lisa atrás, ombros relaxados, cabeça praticamente reta com inclinação mínima. Olhar direto para a câmera, expressão neutra e contemporânea, lábios relaxados e suavemente entreabertos. Cabelo solto com leve movimento, uma mecha podendo cruzar parte do rosto de forma natural, mantendo pelo menos um olho sempre visível. Vestir uma regata preta lisa e minimalista, decote arredondado moderado. Fundo em parede branca lisa. Iluminação natural lateral, criando sombra suave da modelo sobre a parede ao fundo. Quando houver colar, o decote deve deixá-lo totalmente visível sobre o colo.

Qualidade: altíssima resolução, nitidez máxima no rosto e na(s) joia(s), textura de pele natural e realista (sem efeito plástico ou de filtro de beleza), reflexos fisicamente corretos no metal, cores fiéis. Mãos e dedos, quando aparecerem, devem ter anatomia perfeita — sempre cinco dedos, nunca deformados, fundidos ou duplicados, e nunca uma segunda mão ou braço aparecendo acidentalmente no enquadramento. Antes de finalizar, confirme item por item: o rosto ainda é claramente reconhecível como a pessoa da FOTO 1; a quantidade e o tipo de joias são idênticos aos da FOTO 2; nenhuma peça foi inventada, duplicada ou removida. Formato final da imagem: 3:4 (vertical).', NULL, '3:4 (vertical)', 7, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Peças em Você', 'Vento no Cabelo — Brinco', NULL, 'voce_08_vento-no-cabelo', 'Serão anexadas duas fotografias: a FOTO 1, com o rosto da própria assinante, e a FOTO 2, com a(s) joia(s) do produto. A FOTO 1 determina exclusivamente a identidade da modelo: preserve fielmente formato do rosto, olhos, sobrancelhas, nariz, boca, mandíbula, proporções faciais, tom de pele e cabelo (cor, comprimento e textura reais) — a pessoa da imagem final deve continuar claramente reconhecível como a mesma pessoa da FOTO 1. Não a transforme em um rosto genérico, não rejuvenesça, não altere suas feições ou idade aparente. A FOTO 2 determina exclusivamente as joias: identifique exatamente quantas peças e de que tipo existem nela e utilize somente essas peças, na mesma quantidade — nunca invente, duplique, remova ou substitua nenhuma peça; preserve formato, proporções, espessura, acabamento, brilho, cor do metal, pedras e todos os detalhes originais. Se a FOTO 2 contiver outra pessoa, ignore completamente essa pessoa — rosto, corpo, pele, cabelo, roupa e pose não servem de referência, apenas as joias. Nunca misture as duas fotos: cabelo e tom de pele vêm sempre da FOTO 1; joias vêm sempre da FOTO 2. Se determinado tipo de joia não existir na FOTO 2, ele não deve aparecer na imagem final sob nenhuma hipótese.

Composição: retrato fechado frontal, corpo praticamente reto e relaxado, cabeça reta, olhar direto para a câmera. O cabelo aparece solto e movimentado lateralmente por vento, com uma mecha cruzando parte do rosto e um dos olhos, mantendo a outra metade do rosto e uma orelha completamente visíveis. Expressão tranquila e natural. Vestir uma camisa social clara aberta nos ombros. Fundo liso e neutro. Iluminação lateral suave, simulando luz de sol filtrada. Quando houver brinco, a orelha visível deve ficar totalmente livre de cabelo para destacá-lo.

Qualidade: altíssima resolução, nitidez máxima no rosto e na(s) joia(s), textura de pele natural e realista (sem efeito plástico ou de filtro de beleza), reflexos fisicamente corretos no metal, cores fiéis. Mãos e dedos, quando aparecerem, devem ter anatomia perfeita — sempre cinco dedos, nunca deformados, fundidos ou duplicados, e nunca uma segunda mão ou braço aparecendo acidentalmente no enquadramento. Antes de finalizar, confirme item por item: o rosto ainda é claramente reconhecível como a pessoa da FOTO 1; a quantidade e o tipo de joias são idênticos aos da FOTO 2; nenhuma peça foi inventada, duplicada ou removida. Formato final da imagem: 3:4 (vertical).', NULL, '3:4 (vertical)', 8, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Peças em Você', 'Apoiada em Cadeira — Pulseira', NULL, 'voce_09_apoiada-em-cadeira', 'Serão anexadas duas fotografias: a FOTO 1, com o rosto da própria assinante, e a FOTO 2, com a(s) joia(s) do produto. A FOTO 1 determina exclusivamente a identidade da modelo: preserve fielmente formato do rosto, olhos, sobrancelhas, nariz, boca, mandíbula, proporções faciais, tom de pele e cabelo (cor, comprimento e textura reais) — a pessoa da imagem final deve continuar claramente reconhecível como a mesma pessoa da FOTO 1. Não a transforme em um rosto genérico, não rejuvenesça, não altere suas feições ou idade aparente. A FOTO 2 determina exclusivamente as joias: identifique exatamente quantas peças e de que tipo existem nela e utilize somente essas peças, na mesma quantidade — nunca invente, duplique, remova ou substitua nenhuma peça; preserve formato, proporções, espessura, acabamento, brilho, cor do metal, pedras e todos os detalhes originais. Se a FOTO 2 contiver outra pessoa, ignore completamente essa pessoa — rosto, corpo, pele, cabelo, roupa e pose não servem de referência, apenas as joias. Nunca misture as duas fotos: cabelo e tom de pele vêm sempre da FOTO 1; joias vêm sempre da FOTO 2. Se determinado tipo de joia não existir na FOTO 2, ele não deve aparecer na imagem final sob nenhuma hipótese.

Composição: modelo em pé, apoiada casualmente no encosto de uma cadeira branca minimalista, um braço apoiado sobre o encosto com o pulso e a mão relaxados e visíveis, o outro braço relaxado ao lado do corpo. Corpo levemente girado em relação à câmera, olhar direto para a lente, expressão serena. Cabelo solto com ondas suaves. Vestir uma camisa de linho bege. Fundo liso em tom areia. Iluminação suave e natural, lateral. Quando houver pulseira, ela deve ficar visível no pulso apoiado sobre o encosto da cadeira.

Qualidade: altíssima resolução, nitidez máxima no rosto e na(s) joia(s), textura de pele natural e realista (sem efeito plástico ou de filtro de beleza), reflexos fisicamente corretos no metal, cores fiéis. Mãos e dedos, quando aparecerem, devem ter anatomia perfeita — sempre cinco dedos, nunca deformados, fundidos ou duplicados, e nunca uma segunda mão ou braço aparecendo acidentalmente no enquadramento. Antes de finalizar, confirme item por item: o rosto ainda é claramente reconhecível como a pessoa da FOTO 1; a quantidade e o tipo de joias são idênticos aos da FOTO 2; nenhuma peça foi inventada, duplicada ou removida. Formato final da imagem: 3:4 (vertical).', NULL, '3:4 (vertical)', 9, 'a_gerar') on conflict (nome_referencia) do nothing;
insert into public.reference_photos (categoria, tipo_peca, pose, data_comemorativa, nome_referencia, prompt_mestre, perfis_sugeridos, aspecto, ordem, status) values ('evergreen', 'Peças em Você', 'Espelho com Celular — Brinco', NULL, 'voce_10_espelho-com-celular', 'Serão anexadas duas fotografias: a FOTO 1, com o rosto da própria assinante, e a FOTO 2, com a(s) joia(s) do produto. A FOTO 1 determina exclusivamente a identidade da modelo: preserve fielmente formato do rosto, olhos, sobrancelhas, nariz, boca, mandíbula, proporções faciais, tom de pele e cabelo (cor, comprimento e textura reais) — a pessoa da imagem final deve continuar claramente reconhecível como a mesma pessoa da FOTO 1. Não a transforme em um rosto genérico, não rejuvenesça, não altere suas feições ou idade aparente. A FOTO 2 determina exclusivamente as joias: identifique exatamente quantas peças e de que tipo existem nela e utilize somente essas peças, na mesma quantidade — nunca invente, duplique, remova ou substitua nenhuma peça; preserve formato, proporções, espessura, acabamento, brilho, cor do metal, pedras e todos os detalhes originais. Se a FOTO 2 contiver outra pessoa, ignore completamente essa pessoa — rosto, corpo, pele, cabelo, roupa e pose não servem de referência, apenas as joias. Nunca misture as duas fotos: cabelo e tom de pele vêm sempre da FOTO 1; joias vêm sempre da FOTO 2. Se determinado tipo de joia não existir na FOTO 2, ele não deve aparecer na imagem final sob nenhuma hipótese.

Composição: modelo em pé diante de um espelho de moldura fina preta com cantos arredondados, segurando um smartphone com as duas mãos em frente ao rosto, cobrindo boa parte dele — apenas testa, cabelo, mandíbula e uma orelha permanecem visíveis. Cabelo solto, penteado atrás da orelha visível. Vestir uma camisa branca oversized com um ombro levemente à mostra. Fundo minimalista, parede lisa em cinza muito claro. Iluminação suave, sugerindo uma janela fora do enquadramento, incidindo lateralmente. Quando houver brinco, a orelha visível deve permanecer totalmente livre de cabelo para destacá-lo.

Qualidade: altíssima resolução, nitidez máxima no rosto e na(s) joia(s), textura de pele natural e realista (sem efeito plástico ou de filtro de beleza), reflexos fisicamente corretos no metal, cores fiéis. Mãos e dedos, quando aparecerem, devem ter anatomia perfeita — sempre cinco dedos, nunca deformados, fundidos ou duplicados, e nunca uma segunda mão ou braço aparecendo acidentalmente no enquadramento. Antes de finalizar, confirme item por item: o rosto ainda é claramente reconhecível como a pessoa da FOTO 1; a quantidade e o tipo de joias são idênticos aos da FOTO 2; nenhuma peça foi inventada, duplicada ou removida. Formato final da imagem: 3:4 (vertical).', NULL, '3:4 (vertical)', 10, 'a_gerar') on conflict (nome_referencia) do nothing;
