-- Parte 6/17 -- atualiza SOMENTE prompt_mestre
-- Nao mexe em status nem thumbnail_url -- fotos ja aprovadas ficam intactas

update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Posicione o anel em pé, levemente inclinado, mostrando claramente o aro e o detalhe frontal (pedra ou desenho principal). A peça deve parecer fisicamente apoiada e equilibrada, nunca flutuando ou tombada.

Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (RGB 255,255,255), infinito, sem linha de horizonte, sem gradientes, sem textura e sem qualquer elemento decorativo. Iluminação de estúdio: uma fonte de luz principal ampla e difusa, uma luz de preenchimento suave do lado oposto para controlar sombras, e uma luz de contorno sutil para destacar a silhueta. Reflexos no metal limpos, contínuos e fisicamente corretos, sem brilhos estourados. Sombra de contato única, suave e difusa, com leve gradiente natural logo abaixo da peça. Lente equivalente entre 85mm e 105mm, foco perfeitamente nítido em toda a peça, sem distorção de perspectiva.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'anel_still-branco-packshot';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas a mão e os dedos, evidenciando a peça de forma natural.

Fotografia editorial extremamente realista para catálogo premium de joias, produzida como uma campanha de joalheria de luxo. Enquadramento fechado, mostrando apenas a mão e os dedos — nunca mostrar rosto, olhos, boca, nariz, cabelo ou outras partes do corpo além das indicadas. A pele deve ter aparência extremamente natural, saudável e uniforme, com tom: [PERFIL]. Criar uma única faixa de sombra diagonal, contínua e bem definida, inclinada aproximadamente 45°, atravessando a composição como luz entrando por uma janela — a sombra nunca deve cruzar ou escurecer a peça, que deve permanecer completamente iluminada e em destaque. Vestuário minimalista em tecido acetinado ou seda fosca, em tom off-white, extremamente discreto para não competir com a joia. Lente equivalente entre 85mm e 105mm, profundidade de campo rasa — a pele pode ficar levemente desfocada, mas a peça deve permanecer perfeitamente nítida. Fundo neutro (cinza quente muito suave ou bege acinzentado), sem textura, objetos ou elementos decorativos. Não adicionar outras joias, acessórios ou maquiagem chamativa.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Mostre exatamente uma mão, com exatamente cinco dedos anatomicamente corretos — nunca dedos extras, dedos fundidos, articulações deformadas ou uma segunda mão/braço aparecendo parcialmente no enquadramento. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'anel_still-humanizado';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Posicione o anel em pé, levemente inclinado, mostrando claramente o aro e o detalhe frontal (pedra ou desenho principal). A peça deve parecer fisicamente apoiada e equilibrada, nunca flutuando ou tombada.

Fotografia editorial de joias com estética minimalista, sofisticada e contemporânea, semelhante a campanhas de marcas de luxo. A peça deve estar apoiada sobre um tecido branco ou off-white premium, fosco, encorpado, com textura delicada semelhante a crepe de seda estruturado, moldado à mão em ondas amplas e curvas orgânicas — nunca padrões repetitivos, simetria perfeita ou dobras geométricas/espirais matematicamente exatas (isso denuncia aparência de imagem gerada por IA). Câmera em ângulo de aproximadamente 45°, lente macro equivalente a 85-100mm, enquadramento em close-up com a peça ocupando cerca da metade da imagem. Iluminação natural extremamente suave e difusa, como luz de uma grande janela lateral, criando sombras delicadas entre as dobras do tecido. Paleta restrita a branco quente, marfim e creme suave. Não adicionar flores, folhas, pedras decorativas, madeira, embalagens, mãos, pessoas ou qualquer elemento decorativo.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'anel_still-com-sombra-editorial';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Posicione o anel em pé, levemente inclinado, mostrando claramente o aro e o detalhe frontal (pedra ou desenho principal). A peça deve parecer fisicamente apoiada e equilibrada, nunca flutuando ou tombada.

Fotografia still editorial sobre uma superfície de linho bege, de formato orgânico e bordas irregulares, apoiada sobre um tecido acetinado em tom bege claro e quente. Câmera em perspectiva oblíqua, entre 45° e 55° acima da superfície — nunca totalmente frontal nem top-down perfeitamente perpendicular; a composição pode aparecer levemente rotacionada dentro do quadro. Iluminação profissional de estúdio inspirada em luz solar suave entrando lateralmente, criando sombras pequenas e realistas que mostram a peça fisicamente apoiada sobre a superfície. Contraste moderado, cena clara, quente e sofisticada — evitar sombras muito escuras ou iluminação dramática.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'anel_still-em-superficie-texturizada';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas a mão e os dedos, evidenciando a peça de forma natural.

Fotografia lifestyle editorial para redes sociais e e-commerce. Enquadramento fechado o suficiente para não mostrar o rosto da modelo — foco em a mão e os dedos usando a peça de forma natural, em um gesto espontâneo do dia a dia, compatível com o tipo de peça. Iluminação natural suave, como luz de uma janela lateral ampla, sem fonte artificial. Fundo desfocado (profundidade de campo rasa), sugerindo um ambiente interno elegante e minimalista, sem elementos que disputem atenção com a joia. Tons neutros e quentes (branco, off-white, bege). A peça deve permanecer perfeitamente nítida e iluminada, com reflexos naturais e fisicamente corretos no metal.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Mostre exatamente uma mão, com exatamente cinco dedos anatomicamente corretos — nunca dedos extras, dedos fundidos, articulações deformadas ou uma segunda mão/braço aparecendo parcialmente no enquadramento. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'anel_lifestyle-com-modelo';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Posicione as duas alianças em pé, lado a lado, uma levemente sobreposta à outra, ambas fisicamente equilibradas sobre a superfície — nunca flutuando.

Fotografia still de produto (packshot) profissional para e-commerce. Fundo branco puro (RGB 255,255,255), infinito, sem linha de horizonte, sem gradientes, sem textura e sem qualquer elemento decorativo. Iluminação de estúdio: uma fonte de luz principal ampla e difusa, uma luz de preenchimento suave do lado oposto para controlar sombras, e uma luz de contorno sutil para destacar a silhueta. Reflexos no metal limpos, contínuos e fisicamente corretos, sem brilhos estourados. Sombra de contato única, suave e difusa, com leve gradiente natural logo abaixo da peça. Lente equivalente entre 85mm e 105mm, foco perfeitamente nítido em toda a peça, sem distorção de perspectiva.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'alianca_still-branco-packshot';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas as mãos entrelaçadas, próximas ao dedo anelar, evidenciando a peça de forma natural.

Fotografia editorial extremamente realista para catálogo premium de joias, produzida como uma campanha de joalheria de luxo. Enquadramento fechado, mostrando apenas as mãos entrelaçadas, próximas ao dedo anelar — nunca mostrar rosto, olhos, boca, nariz, cabelo ou outras partes do corpo além das indicadas. A pele deve ter aparência extremamente natural, saudável e uniforme, com tom: [PERFIL]. Criar uma única faixa de sombra diagonal, contínua e bem definida, inclinada aproximadamente 45°, atravessando a composição como luz entrando por uma janela — a sombra nunca deve cruzar ou escurecer a peça, que deve permanecer completamente iluminada e em destaque. Vestuário minimalista em tecido acetinado ou seda fosca, em tom off-white, extremamente discreto para não competir com a joia. Lente equivalente entre 85mm e 105mm, profundidade de campo rasa — a pele pode ficar levemente desfocada, mas a peça deve permanecer perfeitamente nítida. Fundo neutro (cinza quente muito suave ou bege acinzentado), sem textura, objetos ou elementos decorativos. Não adicionar outras joias, acessórios ou maquiagem chamativa.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Mostre exatamente duas mãos entrelaçadas, cada uma com exatamente cinco dedos anatomicamente corretos — nunca dedos extras, fundidos ou deformados. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'alianca_still-humanizado';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Posicione as duas alianças em pé, lado a lado, uma levemente sobreposta à outra, ambas fisicamente equilibradas sobre a superfície — nunca flutuando.

Fotografia editorial de joias com estética minimalista, sofisticada e contemporânea, semelhante a campanhas de marcas de luxo. A peça deve estar apoiada sobre um tecido branco ou off-white premium, fosco, encorpado, com textura delicada semelhante a crepe de seda estruturado, moldado à mão em ondas amplas e curvas orgânicas — nunca padrões repetitivos, simetria perfeita ou dobras geométricas/espirais matematicamente exatas (isso denuncia aparência de imagem gerada por IA). Câmera em ângulo de aproximadamente 45°, lente macro equivalente a 85-100mm, enquadramento em close-up com a peça ocupando cerca da metade da imagem. Iluminação natural extremamente suave e difusa, como luz de uma grande janela lateral, criando sombras delicadas entre as dobras do tecido. Paleta restrita a branco quente, marfim e creme suave. Não adicionar flores, folhas, pedras decorativas, madeira, embalagens, mãos, pessoas ou qualquer elemento decorativo.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'alianca_still-com-sombra-editorial';
