-- Parte 12/17 -- atualiza SOMENTE prompt_mestre
-- Nao mexe em status nem thumbnail_url -- fotos ja aprovadas ficam intactas

update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Apoie o colar completamente sobre a superfície, deixando a corrente cair em curvas amplas e orgânicas, como o peso natural do metal realmente se comportaria — nunca reproduza o formato exato da foto original. Nunca crie círculos perfeitos, ovais, corações, gotas ou curvas espelhadas/simétricas dos dois lados; cada lado da corrente deve ter um desenho diferente, com raios e comprimentos de curva variados. Se houver pingente, ele deve ser o ponto focal da composição.

Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.

Fotografia editorial de joias com estética minimalista, sofisticada e contemporânea, semelhante a campanhas de marcas de luxo. A peça deve estar apoiada sobre um tecido branco ou off-white premium, fosco, encorpado, com textura delicada semelhante a crepe de seda estruturado, moldado à mão em ondas amplas e curvas orgânicas — nunca padrões repetitivos, simetria perfeita ou dobras geométricas/espirais matematicamente exatas (isso denuncia aparência de imagem gerada por IA). Câmera em ângulo de aproximadamente 45°, lente macro equivalente a 85-100mm, enquadramento em close-up com a peça ocupando cerca da metade da imagem. Iluminação natural extremamente suave e difusa, como luz de uma grande janela lateral, criando sombras delicadas entre as dobras do tecido. Paleta restrita a branco quente, marfim e creme suave. Não adicionar flores, folhas, pedras decorativas, madeira, embalagens, mãos, pessoas ou qualquer elemento decorativo.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-das-criancas_colar_still-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas o colo, as clavículas e a parte inferior do pescoço, terminando imediatamente abaixo da mandíbula, evidenciando a peça de forma natural.

Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.

Fotografia editorial extremamente realista para catálogo premium de joias, produzida como uma campanha de joalheria de luxo. Enquadramento fechado, mostrando apenas o colo, as clavículas e a parte inferior do pescoço, terminando imediatamente abaixo da mandíbula — nunca mostrar rosto, olhos, boca, nariz, cabelo ou outras partes do corpo além das indicadas. A pele deve ter aparência extremamente natural, saudável e uniforme, com tom: [PERFIL]. Criar uma única faixa de sombra diagonal, contínua e bem definida, inclinada aproximadamente 45°, atravessando a composição como luz entrando por uma janela — a sombra nunca deve cruzar ou escurecer a peça, que deve permanecer completamente iluminada e em destaque. Vestuário minimalista em tecido acetinado ou seda fosca, em tom off-white, extremamente discreto para não competir com a joia. Lente equivalente entre 85mm e 105mm, profundidade de campo rasa — a pele pode ficar levemente desfocada, mas a peça deve permanecer perfeitamente nítida. Fundo neutro (cinza quente muito suave ou bege acinzentado), sem textura, objetos ou elementos decorativos. Não adicionar outras joias, acessórios ou maquiagem chamativa.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-das-criancas_colar_lifestyle-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Posicione o anel em pé, levemente inclinado, mostrando claramente o aro e o detalhe frontal (pedra ou desenho principal). A peça deve parecer fisicamente apoiada e equilibrada, nunca flutuando ou tombada.

Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.

Fotografia editorial de joias com estética minimalista, sofisticada e contemporânea, semelhante a campanhas de marcas de luxo. A peça deve estar apoiada sobre um tecido branco ou off-white premium, fosco, encorpado, com textura delicada semelhante a crepe de seda estruturado, moldado à mão em ondas amplas e curvas orgânicas — nunca padrões repetitivos, simetria perfeita ou dobras geométricas/espirais matematicamente exatas (isso denuncia aparência de imagem gerada por IA). Câmera em ângulo de aproximadamente 45°, lente macro equivalente a 85-100mm, enquadramento em close-up com a peça ocupando cerca da metade da imagem. Iluminação natural extremamente suave e difusa, como luz de uma grande janela lateral, criando sombras delicadas entre as dobras do tecido. Paleta restrita a branco quente, marfim e creme suave. Não adicionar flores, folhas, pedras decorativas, madeira, embalagens, mãos, pessoas ou qualquer elemento decorativo.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-das-criancas_anel_still-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas a mão e os dedos, evidenciando a peça de forma natural.

Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.

Fotografia editorial extremamente realista para catálogo premium de joias, produzida como uma campanha de joalheria de luxo. Enquadramento fechado, mostrando apenas a mão e os dedos — nunca mostrar rosto, olhos, boca, nariz, cabelo ou outras partes do corpo além das indicadas. A pele deve ter aparência extremamente natural, saudável e uniforme, com tom: [PERFIL]. Criar uma única faixa de sombra diagonal, contínua e bem definida, inclinada aproximadamente 45°, atravessando a composição como luz entrando por uma janela — a sombra nunca deve cruzar ou escurecer a peça, que deve permanecer completamente iluminada e em destaque. Vestuário minimalista em tecido acetinado ou seda fosca, em tom off-white, extremamente discreto para não competir com a joia. Lente equivalente entre 85mm e 105mm, profundidade de campo rasa — a pele pode ficar levemente desfocada, mas a peça deve permanecer perfeitamente nítida. Fundo neutro (cinza quente muito suave ou bege acinzentado), sem textura, objetos ou elementos decorativos. Não adicionar outras joias, acessórios ou maquiagem chamativa.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Mostre exatamente uma mão, com exatamente cinco dedos anatomicamente corretos — nunca dedos extras, dedos fundidos, articulações deformadas ou uma segunda mão/braço aparecendo parcialmente no enquadramento. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-das-criancas_anel_lifestyle-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Apoie a pulseira formando uma curva aberta e natural sobre a superfície, como se tivesse caído naturalmente — nunca um círculo perfeitamente fechado.

Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.

Fotografia editorial de joias com estética minimalista, sofisticada e contemporânea, semelhante a campanhas de marcas de luxo. A peça deve estar apoiada sobre um tecido branco ou off-white premium, fosco, encorpado, com textura delicada semelhante a crepe de seda estruturado, moldado à mão em ondas amplas e curvas orgânicas — nunca padrões repetitivos, simetria perfeita ou dobras geométricas/espirais matematicamente exatas (isso denuncia aparência de imagem gerada por IA). Câmera em ângulo de aproximadamente 45°, lente macro equivalente a 85-100mm, enquadramento em close-up com a peça ocupando cerca da metade da imagem. Iluminação natural extremamente suave e difusa, como luz de uma grande janela lateral, criando sombras delicadas entre as dobras do tecido. Paleta restrita a branco quente, marfim e creme suave. Não adicionar flores, folhas, pedras decorativas, madeira, embalagens, mãos, pessoas ou qualquer elemento decorativo.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-das-criancas_pulseira_still-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas o pulso, evidenciando a peça de forma natural.

Tema visual: Dia das Crianças. Paleta de cores: tons pastéis vibrantes (amarelo, azul-bebê, rosa-claro). Elementos/props de cena: pequenos balões desfocados ao fundo, ambiente lúdico. Clima geral: leve, alegre e descontraído.

Fotografia editorial extremamente realista para catálogo premium de joias, produzida como uma campanha de joalheria de luxo. Enquadramento fechado, mostrando apenas o pulso — nunca mostrar rosto, olhos, boca, nariz, cabelo ou outras partes do corpo além das indicadas. A pele deve ter aparência extremamente natural, saudável e uniforme, com tom: [PERFIL]. Criar uma única faixa de sombra diagonal, contínua e bem definida, inclinada aproximadamente 45°, atravessando a composição como luz entrando por uma janela — a sombra nunca deve cruzar ou escurecer a peça, que deve permanecer completamente iluminada e em destaque. Vestuário minimalista em tecido acetinado ou seda fosca, em tom off-white, extremamente discreto para não competir com a joia. Lente equivalente entre 85mm e 105mm, profundidade de campo rasa — a pele pode ficar levemente desfocada, mas a peça deve permanecer perfeitamente nítida. Fundo neutro (cinza quente muito suave ou bege acinzentado), sem textura, objetos ou elementos decorativos. Não adicionar outras joias, acessórios ou maquiagem chamativa.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Mostre exatamente um pulso e uma mão, com exatamente cinco dedos anatomicamente corretos — nunca dedos extras, fundidos ou uma segunda mão aparecendo no enquadramento. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-das-criancas_pulseira_lifestyle-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: Deixe um brinco apoiado em pé, em ângulo de aproximadamente 45° em relação à câmera, e o outro brinco deitado naturalmente sobre a superfície ao lado. Caso a peça tenha tarraxa, mantenha uma tarraxa presa em cada brinco — nunca deixe a tarraxa solta ou separada da peça.

Tema visual: Dia dos Pais. Paleta de cores: tons de azul-marinho e cinza-grafite. Elementos/props de cena: madeira escura, textura de couro ao fundo desfocado. Clima geral: sóbrio, elegante e masculino.

Fotografia editorial de joias com estética minimalista, sofisticada e contemporânea, semelhante a campanhas de marcas de luxo. A peça deve estar apoiada sobre um tecido branco ou off-white premium, fosco, encorpado, com textura delicada semelhante a crepe de seda estruturado, moldado à mão em ondas amplas e curvas orgânicas — nunca padrões repetitivos, simetria perfeita ou dobras geométricas/espirais matematicamente exatas (isso denuncia aparência de imagem gerada por IA). Câmera em ângulo de aproximadamente 45°, lente macro equivalente a 85-100mm, enquadramento em close-up com a peça ocupando cerca da metade da imagem. Iluminação natural extremamente suave e difusa, como luz de uma grande janela lateral, criando sombras delicadas entre as dobras do tecido. Paleta restrita a branco quente, marfim e creme suave. Não adicionar flores, folhas, pedras decorativas, madeira, embalagens, mãos, pessoas ou qualquer elemento decorativo.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-dos-pais_brinco_still-com-tema';
update public.reference_photos set prompt_mestre = 'Utilize exclusivamente a joia da fotografia anexada como referência do produto. Antes de gerar, identifique exatamente quantas peças e quantas unidades de cada peça existem na fotografia anexada (por exemplo, um par de brincos conta como duas unidades) e reproduza exatamente essa mesma quantidade na imagem final — nunca invente, duplique, repita, clone, remova ou complete o conjunto adicionando peças, pingentes, pedras ou componentes que não estejam fisicamente presentes na foto original. Se a foto anexada não contiver determinado tipo de peça (por exemplo, não houver anel), essa peça não deve aparecer na imagem final sob nenhuma hipótese. Preserve com fidelidade absoluta: formato, proporções, espessura, acabamento, brilho, textura, cor do metal, pedras (corte, tamanho e posição), cravação, fechos e elos, e todos os demais detalhes originais da peça. Não redesenhe, reinterprete, estilize, complete, corrija ou invente nenhuma característica da joia — reproduza exatamente o que existe na imagem original. Não utilize a foto anexada como referência de cenário, iluminação, enquadramento ou composição — ela serve apenas para identificar a peça, sua quantidade exata e seus detalhes exatos; remova completamente quaisquer objetos, mãos ou fundos presentes na foto original. Atenção especial à espessura de correntes, elos e fios: é um erro comum de IA generativa deixar correntes finas e delicadas mais grossas, mais vistosas ou mais robustas do que a peça real. A corrente gerada precisa ter exatamente a mesma espessura, o mesmo diâmetro de elo e a mesma delicadeza da foto original — NUNCA mais grossa, mais larga ou mais chamativa do que o original, mesmo que isso a deixe visualmente mais sutil ou difícil de perceber na imagem gerada.

Composição: mostrar apenas a orelha e a lateral do rosto (apenas esses elementos — não mostrar o restante do rosto), evidenciando a peça de forma natural.

Tema visual: Dia dos Pais. Paleta de cores: tons de azul-marinho e cinza-grafite. Elementos/props de cena: madeira escura, textura de couro ao fundo desfocado. Clima geral: sóbrio, elegante e masculino.

Fotografia editorial extremamente realista para catálogo premium de joias, produzida como uma campanha de joalheria de luxo. Enquadramento fechado, mostrando apenas a orelha e a lateral do rosto (apenas esses elementos — não mostrar o restante do rosto) — nunca mostrar rosto, olhos, boca, nariz, cabelo ou outras partes do corpo além das indicadas. A pele deve ter aparência extremamente natural, saudável e uniforme, com tom: [PERFIL]. Criar uma única faixa de sombra diagonal, contínua e bem definida, inclinada aproximadamente 45°, atravessando a composição como luz entrando por uma janela — a sombra nunca deve cruzar ou escurecer a peça, que deve permanecer completamente iluminada e em destaque. Vestuário minimalista em tecido acetinado ou seda fosca, em tom off-white, extremamente discreto para não competir com a joia. Lente equivalente entre 85mm e 105mm, profundidade de campo rasa — a pele pode ficar levemente desfocada, mas a peça deve permanecer perfeitamente nítida. Fundo neutro (cinza quente muito suave ou bege acinzentado), sem textura, objetos ou elementos decorativos. Não adicionar outras joias, acessórios ou maquiagem chamativa.

Qualidade: altíssima resolução, nitidez máxima na joia, excelente alcance dinâmico, texturas naturais, reflexos fisicamente corretos, cores absolutamente fiéis, acabamento fotográfico profissional. Eliminar completamente aparência de renderização 3D, ruído digital, granulado, halos ou qualquer aspecto artificial típico de imagem gerada por IA. A peça não deve parecer flutuando, tombada ou fora de escala — preserve rigorosamente suas proporções e comportamento físico real. Garanta anatomia perfeita da orelha e do lóbulo — sem deformações, sem uma segunda orelha ou rosto fantasma aparecendo no enquadramento. Antes de finalizar, confirme item por item: a quantidade de peças geradas é idêntica à da foto original (nem a mais, nem a menos); nenhuma peça, pingente ou pedra foi inventado, duplicado ou removido; todos os detalhes de acabamento batem com o original. Formato final da imagem: 3:4 (vertical).' where nome_referencia = 'dia-dos-pais_brinco_lifestyle-com-tema';
